### ISSUE TITLE
Benchmarks and unit tests

### ISSUE THREAD

**Issue by zzawadz** [mi2-warsaw/FSelectorRcpp#14]
There is a directory for benchmarks - inst/benchmarks, so we can use it:)

For unit test we can use testthat http://r-pkgs.had.co.nz/tests.html - it's simple and easy:)

**Comment by MarcinKosinski** [comment]
So for unit tests -> I've changed loading packages in testthat and added them to Suggests in DESC and in travis yaml https://github.com/mi2-warsaw/FSelectorRcpp/commit/d8b5480d5f7ab7ff441d8bd250e2ce88ae0864e0

**Comment by MarcinKosinski** [comment]
You are testing FSelector against FSelectorRcpp (you are loading them in testthat) so I have to add them do `suggests` in DESCRIPTION`. Maybe it isn't the best idea to test our package against FSelector since we are adding`Suggests`that is way long :P maybe we could have it in`benchmarks`directory which woul dbe added to`.Rbuildignore`and then we could remove`FSelector, RWeka, entropy` from Sugeests in DESC?

**Comment by MarcinKosinski** [comment]
OK RWeka/FSelector and other benchmarked packages are in `suggests` section of `DESCRIPTION` file so they will not be installed with FSelectorRcpp during regular package installation.
